add august edition
trianglephp/latest-in-php pull request #18
Opened 2018-08-17 13:21 UTC by flashadvocate

2018-08-17 13:36 UTC, cmgmyr requested changes
quick change to the TOC

2018-08-17 13:36 UTC, cmgmyr commented on TOC.md
> +  * August: [raw](2018/03.md) | [slides](https://speakerdeck.com/flashadvocate/latest-in-php-august-edition)
`08.md` 😉

2018-08-18 15:23 UTC, flashadvocate commented
Oops, sorry about that. Fixed :)

2018-08-18 15:56 UTC, cmgmyr approved these changes
Thanks!

2018-08-18 15:56 UTC, merged