Add september presentation
trianglephp/latest-in-php pull request #8
Opened 2017-09-26 21:10 UTC by flashadvocate

2017-09-26 21:11 UTC, flashadvocate commented
You may want to squash. Let me know if you'd like me to take care of this on my end and resubmit.

2017-09-27 13:09 UTC, cmgmyr requested changes

2017-09-27 13:09 UTC, cmgmyr commented on .gitignore
> +.idea/
You can probably remove this file, these should go in your global gitignore file 🙂

2017-09-27 13:09 UTC, cmgmyr commented on 2017/09.md
> +# Tonight @ TrianglePHP
This schedule is going to be a little different - the presentation is actually going to be before the "What's New" Do you want to move this to the first slide?

2017-09-27 13:10 UTC, cmgmyr commented
I can squash on the merge, so no need to worry about it - thanks!

2017-09-28 00:02 UTC, cmgmyr commented
Maybe add a quick mention about https://hacktoberfest.digitalocean.com/ too?

2017-09-28 03:55 UTC, flashadvocate commented on 2017/09.md
> +# Tonight @ TrianglePHP
If the latest in php prez is going last, I can take out this part entirely

2017-09-28 12:14 UTC, cmgmyr approved these changes

2017-09-28 12:14 UTC, cmgmyr commented
Looks great!

2017-09-28 12:14 UTC, merged